name: OrangeFox - Builder

on:
  workflow_dispatch:
  push:

jobs:
  build:
    name: 🦊 Building OrangeFox Recovery
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    permissions: write-all
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: env default
      run: env

    - name: OrangeFox Build Test
      uses: VannTakashi/OrangeFox-Action-Builder@main
      with:
        USER_NAME: 'VannTakashi'
        USER_EMAIL: 'andreanrevan276@gmail.com'
        DEVICE_TREE: 'https://github.com/VannTakashi/recovery_xiaomi_lake'
        DEVICE_TREE_BRANCH: 'rebase-12.1'
        DEVICE_PATH: 'device/xiaomi/lake'
        DEVICE_NAME: 'lake'
        BUILD_TARGET: 'vendor_boot'
        TG_CHAT_ID: '${{ secrets.TG_CHAT_ID }}'
        TG_TOKEN: '${{ secrets.TG_TOKEN }}'
        MAINTAINER_URL: 'https://files.catbox.moe/qwb0tv.jpg'
        GH_RELEASE: 'true'
